# Generated by Django 4.2.24 on 2025-09-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField()),
                ('commit_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('block_hash', models.CharField(max_length=256, unique=True)),
                ('parent_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('quarantined', models.BooleanField(default=False)),
                ('evidence', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lambda_rate', models.FloatField(default=0.0)),
                ('mu_factor', models.FloatField(default=1.0)),
                ('q_rate', models.FloatField(default=0.0)),
                ('fidelity_k', models.FloatField(default=1.0)),
            ],
        ),
    ]
