# Generated by Django 4.2.24 on 2025-09-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='block_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='block',
            name='block_type',
            field=models.CharField(default='deployment', max_length=20),
        ),
        migrations.AddField(
            model_name='block',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
